USE MASTER

GO

CREATE DATABASE	QuanLyLuongSanPham

GO

USE QuanLyLuongSanPham

GO

/*table Tai Khoan*/
CREATE FUNCTION AUTO_IDTK()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MATK) FROM TAIKHOAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MATK, 3)) FROM TAIKHOAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TK00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'TK0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE TaiKhoan
(
	MATK CHAR(5) PRIMARY KEY CONSTRAINT IDTK DEFAULT DBO.AUTO_IDTK(),
	TENDN NVARCHAR(30) NOT NULL,
	MATKHAU VARCHAR(30) NOT NULL
)

GO

CREATE PROC select_TaiKhoan
as
	SELECT * FROM [dbo].[TaiKhoan]

GO

/*table Ca Lam*/
CREATE FUNCTION AUTO_IDCL()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MACA) FROM CALAMVIEC) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MACA, 3)) FROM CALAMVIEC
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CL00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CL0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE CaLamViec
(
	MACA CHAR(5) PRIMARY KEY CONSTRAINT IDCL DEFAULT DBO.AUTO_IDCL(),
	TENCA NVARCHAR(30) NOT NULL,
	GIOLAM NVARCHAR(30) NOT NULL,
	CALAM NVARCHAR(30) NOT NULL,
	LUONGCA FLOAT
)

GO

CREATE PROC select_CLV
as
	SELECT * FROM [dbo].[CaLamViec]

GO

/*table He So Luong*/
CREATE FUNCTION AUTO_IDHSL()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MAHSL) FROM HESOLUONG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAHSL, 3)) FROM HESOLUONG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HSL00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HSL0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE HeSoLuong
(
	MAHSL CHAR(6) PRIMARY KEY CONSTRAINT IDHSL DEFAULT DBO.AUTO_IDHSL(),
	HESOLUONG FLOAT
)

GO

CREATE PROC select_HSL
as
	SELECT * FROM [dbo].[HeSoLuong]

GO

/*table Phong Ban*/
CREATE FUNCTION AUTO_IDPB()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MAPB) FROM PHONGBAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAPB, 3)) FROM PHONGBAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PB00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'PB0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE PhongBan
(
	MAPB CHAR(5) PRIMARY KEY CONSTRAINT IDPB DEFAULT DBO.AUTO_IDPB(),
	TENPHONGBAN NVARCHAR(30) NOT NULL,
)

GO

CREATE PROC select_PB
as
	SELECT * FROM [dbo].[PhongBan]

GO

/*table SanPham*/
CREATE FUNCTION AUTO_IDSP()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MASP) FROM SANPHAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MASP, 3)) FROM SANPHAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'SP00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'SP0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE SanPham
(
	MASP CHAR(5) PRIMARY KEY CONSTRAINT IDSP DEFAULT DBO.AUTO_IDSP(),
	TENSANPHAM NVARCHAR(30) NOT NULL,
	KIEUDANG NVARCHAR(30) NULL,
	CHATLIEU NVARCHAR(30) NULL,
	SOLUONG INT
)

GO

CREATE PROC select_SP
as
	SELECT * FROM [dbo].[SanPham]

GO

/*table Cong Doan*/
CREATE FUNCTION AUTO_IDCD()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MACD) FROM CONGDOAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MACD, 3)) FROM CONGDOAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE CongDoan
(
	MACD CHAR(5) PRIMARY KEY CONSTRAINT IDCD DEFAULT DBO.AUTO_IDCD(),
	TENCONGDOAN NVARCHAR(60) NOT NULL,
	GIACONGDOAN FLOAT,
	SOLUONG INT,
	MASP CHAR(5) NOT NULL,
	MACDYC CHAR(5) NOT NULL,
	CONSTRAINT fk_MaSP
	FOREIGN KEY(MASP)
	REFERENCES SANPHAM(MASP)
	ON DELETE CASCADE ON UPDATE CASCADE,
)

GO

CREATE PROC select_CD
as
	SELECT * FROM [dbo].[CongDoan]

GO

/*table Nhan Vien Hanh Chinh*/
CREATE FUNCTION AUTO_IDNV()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MANV) FROM NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MANV, 3)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE NhanVien
(
	MANV CHAR(5) PRIMARY KEY CONSTRAINT IDNV DEFAULT DBO.AUTO_IDNV(),
	HOTEN NVARCHAR(60) NOT NULL,
	CMND INT,
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10) NULL,
	LUONGCOBAN FLOAT,
	SODIENTHOAI VARCHAR(11) NULL,
	DIACHI NVARCHAR(60) NULL,
	PHUCAP FLOAT,
	MAHSL CHAR(6) NOT NULL,
	MAPB CHAR(5) NOT NULL,
	CONSTRAINT fk_MaHSLNV
	FOREIGN KEY(MAHSL)
	REFERENCES HESOLUONG(MAHSL)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_MaPhongBanNV
	FOREIGN KEY(MAPB)
	REFERENCES PHONGBAN(MAPB)
	ON DELETE CASCADE ON UPDATE CASCADE,
)

GO

CREATE PROC select_NV
as
	SELECT * FROM [dbo].[NhanVien]

GO

/*table Cong Nhan*/
CREATE FUNCTION AUTO_IDCN()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MACN) FROM CONGNHAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MACN, 3)) FROM CONGNHAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CN00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CN0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE CongNhan
(
	MACN CHAR(5) PRIMARY KEY CONSTRAINT IDCN DEFAULT DBO.AUTO_IDCN(),
	HOTEN NVARCHAR(60) NOT NULL,
	CMND INT,
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10) NULL,
	TAYNGHE NVARCHAR(30) NULL,
	SODIENTHOAI VARCHAR(11) NULL,
	DIACHI NVARCHAR(60) NULL,
	PHUCAP FLOAT,
	MAPB CHAR(5) NOT NULL,
	CONSTRAINT fk_MaPhongBanCN
	FOREIGN KEY(MAPB)
	REFERENCES PHONGBAN(MAPB)
	ON DELETE CASCADE ON UPDATE CASCADE,
)

GO

CREATE PROC select_CN
as
	SELECT * FROM [dbo].[CongNhan]

GO

/*table Cham Cong Nhan Vien*/
CREATE FUNCTION AUTO_IDCCNV()
RETURNS VARCHAR(4)
AS
BEGIN
	DECLARE @ID VARCHAR(4)
	IF (SELECT COUNT(MACONG) FROM CHAMCONGNHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MACONG, 3)) FROM CHAMCONGNHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'C00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'C0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE ChamCongNhanVien
(
	MACONG CHAR(4) PRIMARY KEY CONSTRAINT IDCCNV DEFAULT DBO.AUTO_IDCCNV(),
	NGAYCHAM DATE,
	TRANGTHAI INT,
	NGHIPHEP INT,
	MACA CHAR(5) NOT NULL,
	CONSTRAINT fk_MaCaLamNV
	FOREIGN KEY(MACA)
	REFERENCES CALAMVIEC(MACA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MANV CHAR(5) NOT NULL,
	CONSTRAINT fk_MaNVCC
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN(MANV)
	ON DELETE CASCADE ON UPDATE CASCADE,
)

GO

CREATE PROC select_CCNV
as
	SELECT * FROM [dbo].[ChamCongNhanVien]

GO

/*table Phan Cong Cong Nhan*/
CREATE FUNCTION AUTO_IDPC()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MAPC) FROM PHANCONG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAPC, 3)) FROM PHANCONG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PC00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'PC0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE PhanCong
(
	MAPC CHAR(5) PRIMARY KEY CONSTRAINT IDPC DEFAULT DBO.AUTO_IDPC(),
	SOLUONGCANLAM INT,
	MACN CHAR(5) NOT NULL,
	CONSTRAINT fk_MaPCCN
	FOREIGN KEY(MACN)
	REFERENCES CONGNHAN(MACN)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MACD CHAR(5) NOT NULL,
	CONSTRAINT fk_MaCDSP
	FOREIGN KEY(MACD)
	REFERENCES CONGDOAN(MACD)
	ON DELETE CASCADE ON UPDATE CASCADE,
)

GO

CREATE PROC select_PCCN
as
	SELECT * FROM [dbo].[PhanCong]

GO

/*table Cham Cong Cong Nhan*/
CREATE FUNCTION AUTO_IDCCCN()
RETURNS VARCHAR(4)
AS
BEGIN
	DECLARE @ID VARCHAR(4)
	IF (SELECT COUNT(MACONG) FROM CHAMCONGCONGNHAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MACONG, 3)) FROM CHAMCONGCONGNHAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'C00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'C0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE ChamCongCongNhan
(
	MACONG CHAR(4) PRIMARY KEY CONSTRAINT IDCCCN DEFAULT DBO.AUTO_IDCCCN(),
	NGAYCHAM DATE,
	SOSANPHAM INT,
	TRANGTHAI INT,
	NGHIPHEP INT,
	MASP CHAR(5) NOT NULL,
	CONSTRAINT fk_MaSPCN
	FOREIGN KEY(MASP)
	REFERENCES SANPHAM(MASP)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MACD CHAR(5) NOT NULL,
	MACA CHAR(5) NOT NULL,
	CONSTRAINT fk_MaCaLamCN
	FOREIGN KEY(MACA)
	REFERENCES CALAMVIEC(MACA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MACN CHAR(5) NOT NULL,
	CONSTRAINT fk_MaCCCN
	FOREIGN KEY(MACN)
	REFERENCES CONGNHAN(MACN)
	ON DELETE CASCADE ON UPDATE CASCADE,

)

GO

CREATE PROC select_CCCN
as
	SELECT * FROM [dbo].[ChamCongCongNhan]

GO

/*table Luong Nhan Vien*/
CREATE FUNCTION AUTO_IDLNV()
RETURNS VARCHAR(4)
AS
BEGIN
	DECLARE @ID VARCHAR(4)
	IF (SELECT COUNT(MALUONG) FROM LUONGNHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MALUONG, 3)) FROM LUONGNHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'L00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'L0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE LuongNhanVien
(
	MALUONG CHAR(4) PRIMARY KEY CONSTRAINT IDLNV DEFAULT DBO.AUTO_IDLNV(),
	THANG INT,
	NAM INT,
	LUONG FLOAT,
	MANV CHAR(5) NOT NULL,
	CONSTRAINT fk_MaNVL
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN(MANV)
	ON DELETE CASCADE ON UPDATE CASCADE,

)

GO

CREATE PROC select_LNV
as
	SELECT * FROM [dbo].[LuongNhanVien]

GO

/*table Luong Cong Nhan*/
CREATE FUNCTION AUTO_IDLCN()
RETURNS VARCHAR(4)
AS
BEGIN
	DECLARE @ID VARCHAR(4)
	IF (SELECT COUNT(MALUONG) FROM LUONGCONGNHAN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MALUONG, 3)) FROM LUONGCONGNHAN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'L00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'L0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

GO

CREATE TABLE LuongCongNhan
(
	MALUONG CHAR(4) PRIMARY KEY CONSTRAINT IDLCN DEFAULT DBO.AUTO_IDLCN(),
	THANG INT,
	NAM INT,
	LUONG FLOAT,
	MACN CHAR(5) NOT NULL,
	CONSTRAINT fk_MaCNL
	FOREIGN KEY(MACN)
	REFERENCES CONGNHAN(MACN)
	ON DELETE CASCADE ON UPDATE CASCADE,

)

GO

CREATE PROC select_LCN
as
	SELECT * FROM [dbo].[LuongCongNhan]

GO

INSERT INTO [dbo].[HeSoLuong]([HESOLUONG])
VALUES(1.0)
INSERT INTO [dbo].[HeSoLuong]([HESOLUONG])
VALUES(1.5)
INSERT INTO [dbo].[HeSoLuong]([HESOLUONG])
VALUES(2.0)
INSERT INTO [dbo].[HeSoLuong]([HESOLUONG])
VALUES(2.5)
INSERT INTO [dbo].[HeSoLuong]([HESOLUONG])
VALUES(3.0)
INSERT INTO [dbo].[HeSoLuong]([HESOLUONG])
VALUES(3.5)

INSERT INTO [dbo].[PhongBan]([TENPHONGBAN])
VALUES (N'Ban Quản Lý')
INSERT INTO [dbo].[PhongBan]([TENPHONGBAN])
VALUES (N'Ban Sản Xuất')

INSERT INTO [dbo].[CaLamViec]([TENCA],[GIOLAM],[CALAM],[LUONGCA])
VALUES(N'Sáng','8h-12h',N'Ca Sáng', 1.0)
INSERT INTO [dbo].[CaLamViec]([TENCA],[GIOLAM],[CALAM],[LUONGCA])
VALUES(N'Chiều','13h-17h',N'Ca Chiều', 1.0)
INSERT INTO [dbo].[CaLamViec]([TENCA],[GIOLAM],[CALAM],[LUONGCA])
VALUES(N'Tối','18h-22h',N'Ca Tối', 2.0)
INSERT INTO [dbo].[CaLamViec]([TENCA],[GIOLAM],[CALAM],[LUONGCA])
VALUES(N'Sáng','8h-12h',N'Ca Sáng CN', 2.0)
INSERT INTO [dbo].[CaLamViec]([TENCA],[GIOLAM],[CALAM],[LUONGCA])
VALUES(N'Chiều','13h-17h',N'Ca Chiều CN', 2.0)
INSERT INTO [dbo].[CaLamViec]([TENCA],[GIOLAM],[CALAM],[LUONGCA])
VALUES(N'Tối','18h-22h',N'Ca Tối CN', 2.0)